### ISSUE TITLE
【依頼】ProtoSpace挙動確認	

### ISSUE THREAD

**Issue by ubquitouszero** [ubquitouszero/protospace-37323#1]
■Web URL
https://protospace-37323.herokuapp.com/

**Comment by shodai-ito** [comment]
@ubquitouszero さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
##### コメント機能
- [ ] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
空のまま投稿しようとするとエラーになってしまいます。
<img width="697" alt="スクリーンショット 2022-03-19 14 05 13" src="https://user-images.githubusercontent.com/62537107/159107858-f2d821d7-01a3-4a1f-a818-b049a505aa7d.png">


##### ユーザー詳細機能
- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
一部ユーザー名をクリックしても、ユーザー詳細ページへ遷移しません。
<img width="410" alt="スクリーンショット 2022-03-19 14 07 13" src="https://user-images.githubusercontent.com/62537107/159107872-6deb4742-7504-4d39-a600-d008940cf876.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by yusuketono** [comment]
@ubquitouszero さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀

**Comment by ubquitouszero** [comment]
レビューありがとうございました！！！
